version: 2.1

default: &default
  docker:
    - image: circleci/node:13.8.0

jobs:
  build:
    <<: *default
    steps:
      - checkout
      - run: npm i
      - save_cache:
          key: "npm-packages"
          paths:
            - /src
      - run: npm run lint 
  test:
    <<: *default
    steps:
      - checkout
      - restore_cache:
          key: "npm-packages"
      - run: npm i
      - run: npm run test
      


workflows:
  my_workflow:
    jobs:
      - build 
      - test: 
          requires:
            - build 